<?php $title='Seller hub';require_once 'config.php';need_perm('sell');
if(me()['status']!='active'){include 'header.php';echo '<main class="page"><p class="pay">Your seller account is waiting for admin approval. You can start listing once it is approved.</p></main>';include 'footer.php';exit;}
if($_SERVER['REQUEST_METHOD']=='POST'){check();$me=me()['id'];
 if(isset($_POST['prof']))q('UPDATE users SET shop=?,district=?,address=?,about=? WHERE id=?',[trim($_POST['shop']),province($_POST['district'])?$_POST['district']:null,trim($_POST['address']),trim($_POST['about']),$me]);
 if(isset($_POST['np']))q('INSERT INTO products(cat_id,name,descr,price,unit,stock,seller,seller_id,image) VALUES(?,?,?,?,?,?,?,?,?)',[$_POST['cat'],$_POST['name'],$_POST['descr'],(int)$_POST['price'],$_POST['unit'],(int)$_POST['stock'],me()['shop']?:me()['name'],$me,save_img($_FILES['img']??[])]);
 if(isset($_POST['del']))q('DELETE FROM products WHERE id=? AND seller_id=?',[(int)$_POST['del'],$me]);
 if(isset($_POST['stock']))q('UPDATE products SET stock=? WHERE id=? AND seller_id=?',[(int)$_POST['stock'],(int)$_POST['pid'],$me]);
 if(isset($_POST['ship'])){$it=q("SELECT i.order_id FROM order_items i JOIN orders o ON o.id=i.order_id WHERE i.id=? AND i.seller_id=? AND o.status='paid'",[(int)$_POST['ship'],$me])->fetch();
  if($it){q("UPDATE order_items SET item_status='shipped' WHERE id=?",[(int)$_POST['ship']]);
   if(!q("SELECT 1 FROM order_items WHERE order_id=? AND item_status='pending'",[$it['order_id']])->fetch())set_status($it['order_id'],'shipped','All items dispatched by sellers');}}
 header('Location: seller.php');exit;}
include 'header.php';$cats=q('SELECT * FROM categories')->fetchAll();
$rev=q("SELECT SUM(i.qty*i.price) s FROM order_items i JOIN orders o ON o.id=i.order_id WHERE i.seller_id=? AND o.status IN('paid','shipped','delivered')",[me()['id']])->fetch()['s']??0;
$its=q("SELECT i.*,p.name,o.address,o.phone,o.status FROM order_items i JOIN products p ON p.id=i.product_id JOIN orders o ON o.id=i.order_id WHERE i.seller_id=? AND o.status IN('paid','shipped') ORDER BY o.id DESC",[me()['id']])->fetchAll();
$ps=q('SELECT * FROM products WHERE seller_id=? ORDER BY id DESC',[me()['id']])->fetchAll();?>
<main class="page"><h2>Seller hub</h2><div class="kpis"><div class="kpi"><b><?=money($rev)?></b>Confirmed sales</div><div class="kpi"><b><?=count($ps)?></b>Products listed</div><div class="kpi"><b><?=count(array_filter($its,fn($i)=>$i['item_status']=='pending'))?></b>To ship</div><div class="kpi"><b><?=count(array_filter($ps,fn($p)=>$p['stock']<20))?></b>Low stock</div></div>
<p><a class="btn" href="shop.php?id=<?=me()['id']?>">View my public shop</a></p><details><summary>Shop profile and location (buyers nearby see you first)</summary><form method="post" class="f"><input type="hidden" name="t" value="<?=csrf()?>"><input type="hidden" name="prof" value="1"><label>Shop name<input name="shop" value="<?=e(me()['shop'])?>" required></label><label>District<select name="district" required><?=dist_opts(me()['district'])?></select></label><label>Street / sector<input name="address" value="<?=e(me()['address'])?>"></label><label>About your shop<textarea name="about"><?=e(me()['about'])?></textarea></label><button>Save profile</button></form></details>
<h2>Orders to fulfil</h2><?php if(!$its):?><p>No paid orders waiting. Orders appear here once payment is confirmed.</p><?php else:?><table><?php foreach($its as $i):?><tr><td>#<?=$i['order_id']?><td><?=$i['qty']?> × <?=e($i['name'])?><td><?=e($i['address']?:'Pickup')?> · <?=e($i['phone'])?><td><?php if($i['item_status']=='pending'):?><form method="post"><input type="hidden" name="t" value="<?=csrf()?>"><button name="ship" value="<?=$i['id']?>">Mark shipped</button></form><?php else:?>Shipped<?php endif;?></tr><?php endforeach;?></table><?php endif;?>
<h2>List a product</h2><form method="post" class="f" enctype="multipart/form-data"><input type="hidden" name="t" value="<?=csrf()?>"><input type="hidden" name="np" value="1"><label>Name<input name="name" required></label><label>Product photo (JPG, PNG or WEBP, max 2MB)<input type="file" name="img" accept="image/*"></label><label>Category<select name="cat"><?php foreach($cats as $k):?><option value="<?=$k['id']?>"><?=e($k['name'])?></option><?php endforeach;?></select></label><label>Description<textarea name="descr"></textarea></label><label>Price (<?=CUR?>)<input name="price" type="number" required></label><label>Unit<input name="unit" value="piece"></label><label>Stock<input name="stock" type="number" required></label><button>Publish product</button></form>
<h2>Your products</h2><table><?php foreach($ps as $p):?><tr><td><?=e($p['name'])?><td><?=money($p['price'])?><td><form method="post" class="inline"><input type="hidden" name="t" value="<?=csrf()?>"><input type="hidden" name="pid" value="<?=$p['id']?>"><input class="qty" type="number" name="stock" value="<?=$p['stock']?>"><button>Update stock</button></form><td><form method="post"><input type="hidden" name="t" value="<?=csrf()?>"><button name="del" value="<?=$p['id']?>" onclick="return confirm('Delete?')">Delete</button></form></tr><?php endforeach;?></table></main><?php include 'footer.php';
